# Generated by Django 4.2.1 on 2023-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_transaction_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_number',
            field=models.IntegerField(null=True),
        ),
    ]
